### ISSUE TITLE
1.9.0-alpha15 problem

### ISSUE THREAD

**Issue by robertluo** [zhuangxm/boot-lein#2]
current implementation is not compatible with clojure 1.9.0-alpha15.

**Comment by zhuangxm** [comment]
是 core.async 报错吗?
https://groups.google.com/forum/#!msg/clojure/7ZqGTjJoQEQ/vSd8UWLhAwAJ

**Comment by robertluo** [comment]
The bug is at the file line 15. `:or {:keep-project ...}` should be `:or {keep-project ...}`

This destructing bug was found by 1.9.0-alpha15 onwards.

**Comment by robertluo** [comment]
#1
